const {
	env: {
		CI = '',
		TRAVIS_NODE_VERSION = '',
		TRAVIS_BUILD_NUMBER = '',
		BROWSERSTACK_USERNAME = '',
		BROWSERSTACK_ACCESS_KEY = '',
	},
} = process;
Object.assign(exports, {
	CI,
	TRAVIS_NODE_VERSION,
	TRAVIS_BUILD_NUMBER,
	BROWSERSTACK_USERNAME,
	BROWSERSTACK_ACCESS_KEY,
	BROWSERSTACK: Boolean(TRAVIS_NODE_VERSION === '10' && BROWSERSTACK_USERNAME && BROWSERSTACK_ACCESS_KEY),
});
