const {
	CI = '',
	TRAVIS_NODE_VERSION = '',
	TRAVIS_BUILD_NUMBER = '',
	BROWSERSTACK_USERNAME = '',
	BROWSERSTACK_ACCESS_KEY = '',
} = process.env;

module.exports = {
	CI,
	TRAVIS_NODE_VERSION,
	TRAVIS_BUILD_NUMBER,
	BROWSERSTACK_USERNAME,
	BROWSERSTACK_ACCESS_KEY,
	BROWSERSTACK: Boolean(BROWSERSTACK_USERNAME && BROWSERSTACK_ACCESS_KEY),
};
