const {
	TRAVIS_BUILD_NUMBER = '',
	BROWSERSTACK_USERNAME = '',
	BROWSERSTACK_ACCESS_KEY = '',
} = process.env;

module.exports = {
	TRAVIS_BUILD_NUMBER,
	BROWSERSTACK_USERNAME,
	BROWSERSTACK_ACCESS_KEY,
	BROWSERSTACK: Boolean(BROWSERSTACK_USERNAME && BROWSERSTACK_ACCESS_KEY),
};
